# Generated by Django 4.2.5 on 2024-05-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapackage',
            name='display_order',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
