# Generated by Django 4.2.5 on 2024-05-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_datapackage_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('auth0_client', models.TextField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cookie', models.TextField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('data_left', models.CharField(blank=True, max_length=10, null=True)),
                ('sim_number', models.CharField(blank=True, max_length=10, null=True)),
                ('current_balance', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
