# Generated by Django 4.2.5 on 2024-05-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapackage',
            old_name='data_amount',
            new_name='data_qty',
        ),
    ]
