# Generated by Django 4.2.5 on 2024-05-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_data_amount_datapackage_data_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.sim'),
        ),
    ]
