# Generated by Django 4.2.13 on 2024-05-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_datapackage_data_qty_alter_sim_data_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapackage',
            name='data_qty',
            field=models.IntegerField(),
        ),
    ]
