# Generated by Django 4.2.13 on 2024-05-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_datapackage_data_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='data_left_before_logout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sim',
            name='logged_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
