# Generated by Django 4.2.13 on 2024-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_datapackage_data_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='data_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
