# Generated by Django 4.2.5 on 2024-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_sim_data_left_before_logout_sim_logged_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapackage',
            old_name='price',
            new_name='retailer_price',
        ),
        migrations.AddField(
            model_name='datapackage',
            name='vendor_price',
            field=models.DecimalField(decimal_places=2, default=99999, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('vendor', 'Vendor')], default='retailer', max_length=8),
        ),
    ]
