# Generated by Django 4.2.13 on 2024-05-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_sim_data_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='data_left',
            field=models.IntegerField(blank=True, default=5000, null=True),
        ),
    ]
