# Generated by Django 4.2.13 on 2024-05-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_sim_data_left_before_logout_sim_logged_out'),
        ('sales', '0012_alter_sim_data_left'),
    ]

    operations = [
    ]
