# Generated by Django 4.2.5 on 2024-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_rename_price_datapackage_retailer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapackage',
            name='retailer_price',
            field=models.DecimalField(decimal_places=2, default=99999, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='vendor_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('vendor', 'Vendor')], default='vendor', max_length=8),
        ),
    ]
