# Generated by Django 4.2.13 on 2024-05-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_datapackage_retailer_price_and_more'),
        ('sales', '0013_merge_20240525_0631'),
    ]

    operations = [
    ]
