# Generated by Django 4.2.13 on 2024-05-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_admintransaction'),
        ('sales', '0014_merge_20240527_1142'),
    ]

    operations = [
    ]
