# Generated by Django 4.2.13 on 2024-05-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_accounttype_alter_userprofile_account_type_and_more'),
        ('sales', '0015_merge_0014_admintransaction_0014_merge_20240527_1142'),
    ]

    operations = [
    ]
