# Generated by Django 4.2.5 on 2024-05-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_accounttype_alter_userprofile_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='price',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='description',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
