# Generated by Django 4.2.13 on 2024-05-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_merge_20240528_1351'),
        ('sales', '0016_remove_accounttype_price_accounttype_description_and_more'),
    ]

    operations = [
    ]
