# Generated by Django 4.2.5 on 2024-05-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_accounttype_price_accounttype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
