# Generated by Django 4.2.13 on 2024-05-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_merge_20240529_0248'),
        ('sales', '0017_userprofile_expiry_date'),
    ]

    operations = [
    ]
