# Generated by Django 4.2.5 on 2024-06-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_merge_20240529_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='current_balance',
            field=models.CharField(blank=True, default=400000, max_length=10, null=True),
        ),
    ]
