# Generated by Django 4.2.5 on 2024-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_sim_current_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sim',
            options={'ordering': ['sim_number']},
        ),
        migrations.AlterField(
            model_name='sim',
            name='sim_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
