# Generated by Django 4.2.5 on 2024-06-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_sim_options_alter_sim_sim_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sim',
            options={'ordering': ['-sim_number']},
        ),
    ]
