# Generated by Django 4.2.13 on 2024-06-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_sim_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='logged_out',
        ),
        migrations.AddField(
            model_name='sim',
            name='logged_in',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
