# Generated by Django 4.2.13 on 2024-06-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_remove_sim_logged_out_sim_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='investment_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
