# Generated by Django 4.2.13 on 2024-06-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_webhooklog_onlinetransaction_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='header',
            field=models.TextField(default='header'),
        ),
    ]
