# Generated by Django 4.2.13 on 2024-06-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_webhooklog_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetransaction',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_transactions', to='sales.userprofile'),
        ),
    ]
