# Generated by Django 4.2.13 on 2024-06-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_alter_onlinetransaction_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapackage',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, default=99999, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('vendor', 'Vendor'), ('custom', 'Custom')], default='retailer', max_length=8),
        ),
    ]
