# Generated by Django 4.2.13 on 2024-07-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_datapackage_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='data_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
