# Generated by Django 4.2.13 on 2024-07-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_alter_sim_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='is_exhausted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sim',
            name='prev_day_data_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
