# Generated by Django 4.2.13 on 2024-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_sim_is_exhausted_sim_prev_day_data_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='current_balance',
            field=models.CharField(blank=True, default=400000, max_length=10, null=True),
        ),
    ]
