# Generated by Django 4.2.13 on 2024-07-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_userprofile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
