# Generated by Django 4.2.13 on 2024-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_alter_userprofile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tr_response',
            field=models.TextField(blank=True, default='tr_response', null=True),
        ),
    ]
