# Generated by Django 4.2.13 on 2024-07-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_transaction_tr_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_to_invest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
