# Generated by Django 4.2.13 on 2024-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_userprofile_allowed_to_invest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='refresh_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sim',
            name='restock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
