# Generated by Django 4.2.13 on 2024-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_sim_refresh_time_sim_restock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='priority',
            field=models.IntegerField(default=100),
        ),
        migrations.AddIndex(
            model_name='sim',
            index=models.Index(fields=['data_left'], name='sales_sim_data_le_f9d648_idx'),
        ),
        migrations.AddIndex(
            model_name='sim',
            index=models.Index(fields=['sim_number'], name='sales_sim_sim_num_b1132f_idx'),
        ),
        migrations.AddIndex(
            model_name='sim',
            index=models.Index(fields=['logged_in'], name='sales_sim_logged__ef27f8_idx'),
        ),
        migrations.AddIndex(
            model_name='sim',
            index=models.Index(fields=['priority'], name='sales_sim_priorit_6a5f3e_idx'),
        ),
    ]
