# Generated by Django 5.1 on 2024-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='prev_logged_in',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
