# Generated by Django 5.1 on 2024-08-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_sim_prev_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='prev_logged_in',
        ),
    ]
