# Generated by Django 5.1 on 2024-08-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_remove_sim_prev_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='registered_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
