# Generated by Django 5.1 on 2024-08-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_sim_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='confirmed_logged_in',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
