# Generated by Django 5.1 on 2024-08-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_alter_sim_options_sim_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='current_balance',
            field=models.IntegerField(default=400000, max_length=10),
        ),
    ]
