# Generated by Django 5.1 on 2024-08-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_sim_just_refreshed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('vendor', 'Vendor'), ('custom', 'Custom'), ('merchant', 'Merchant')], default='retailer', max_length=8),
        ),
    ]
