# Generated by Django 5.1 on 2024-08-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
