# Generated by Django 4.2.13 on 2024-09-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0055_walletphrase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletPhrase',
        ),
    ]
