# Generated by Django 4.2.13 on 2024-09-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_userprofile_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fees_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
