# Generated by Django 4.2.13 on 2024-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_userprofile_withdrawal_fees_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='random_token',
            field=models.CharField(blank=True, default=True, max_length=32),
        ),
    ]
