# Generated by Django 5.1 on 2024-08-23 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0054_userprofile_referral_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_option', models.CharField(choices=[('banktransfer', 'Bank Transfer'), ('card', 'Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_time', models.DateTimeField(blank=True, null=True)),
                ('bank_account_details', models.TextField(blank=True, max_length=255, null=True)),
                ('card_details', models.TextField(blank=True, max_length=255, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('crypto_option', models.CharField(blank=True, max_length=50, null=True)),
                ('crypto_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_withdrawals', to='sales.userprofile')),
            ],
            options={
                'ordering': ['-request_time'],
            },
        ),
    ]
