# Generated by Django 5.1 on 2024-08-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralwithdrawal',
            name='payment_option',
            field=models.CharField(choices=[('databalance', 'Add to Data Balance'), ('banktransfer', 'Bank Transfer'), ('card', 'Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency')], max_length=20),
        ),
    ]
