# Generated by Django 4.2.13 on 2024-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referralwithdrawal_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralwithdrawal',
            name='payment_option',
            field=models.CharField(choices=[('databalance', 'Add to Investment Balance'), ('banktransfer', 'Bank Transfer'), ('card', 'Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency')], max_length=20),
        ),
    ]
