# Generated by Django 4.2.13 on 2024-06-17 01:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0023_userprofile_investment_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2024, 9, 5, 1, 45, 25, 294568, tzinfo=datetime.timezone.utc))),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.investmenttype')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='sales.userprofile')),
            ],
        ),
    ]
