# Generated by Django 4.2.13 on 2024-06-18 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 10, 47, 16, 9904, tzinfo=datetime.timezone.utc)),
        ),
    ]
