# Generated by Django 4.2.13 on 2024-06-18 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_investment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 17, 38, 2, 158389, tzinfo=datetime.timezone.utc)),
        ),
    ]
