# Generated by Django 4.2.13 on 2024-06-18 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_alter_investment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 17, 41, 37, 556410, tzinfo=datetime.timezone.utc)),
        ),
    ]
