# Generated by Django 4.2.13 on 2024-06-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_alter_investment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
