# Generated by Django 4.2.13 on 2024-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_alter_investment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
