# Generated by Django 4.2.13 on 2024-06-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_investment_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='last_credited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
