# Generated by Django 4.2.13 on 2024-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_investment_last_credited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
