# Generated by Django 4.2.13 on 2024-07-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_alter_investment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.investmenttype'),
        ),
    ]
