# Generated by Django 4.2.13 on 2024-07-19 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_userprofile_allowed_to_invest'),
        ('investments', '0019_investmenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi', to='investments.investment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to='sales.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='InvestmentTransaction',
        ),
    ]
