# Generated by Django 4.2.13 on 2024-07-30 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_sim_priority_sim_sales_sim_data_le_f9d648_idx_and_more'),
        ('investments', '0020_roitransaction_delete_investmenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_option', models.CharField(choices=[('banktransfer', 'Bank Transfer'), ('card', 'Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_time', models.DateTimeField(blank=True, null=True)),
                ('bank_account_details', models.TextField(blank=True, max_length=255, null=True)),
                ('card_details', models.TextField(blank=True, max_length=255, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('crypto_option', models.CharField(blank=True, max_length=50, null=True)),
                ('crypto_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='sales.userprofile')),
            ],
        ),
    ]
