# Generated by Django 4.2.13 on 2024-08-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0021_withdrawal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roitransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-request_time']},
        ),
    ]
