# Generated by Django 5.1 on 2024-08-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0023_remove_investmenttype_tenure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttype',
            name='tenure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
