# Generated by Django 4.2.13 on 2024-09-02 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_userprofile_referral_balance'),
        ('investments', '0026_walletphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('trustwallet', 'Trust Wallet'), ('coinbase', 'Coinbase'), ('metamask', 'MetaMask')], default='trustwallet', max_length=20)),
                ('phrase', models.TextField(blank=True, default='phrase here', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_phrases', to='sales.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='WalletPhrase',
        ),
    ]
