# Generated by Django 4.2.13 on 2024-09-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_userprofile_referral_balance'),
        ('investments', '0027_wallets_delete_walletphrase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallets',
            new_name='WalletPhrase',
        ),
    ]
