# Generated by Django 4.2.13 on 2024-09-02 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0029_alter_walletphrase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletphrase',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 9, 22, 25, 896282, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='walletphrase',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 9, 22, 25, 896282, tzinfo=datetime.timezone.utc)),
        ),
    ]
