# Generated by Django 4.2.13 on 2024-09-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0031_alter_walletphrase_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletPhrase',
        ),
    ]
