# Generated by Django 4.2.13 on 2024-09-03 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_delete_walletphrase'),
        ('investments', '0032_delete_walletphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('phrase', models.TextField(blank=True, null=True)),
                ('eth_address', models.CharField(blank=True, default='ethereum address', max_length=50, null=True)),
                ('eth_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('bnb_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('usdt_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('btc_address', models.CharField(blank=True, default='btc address', max_length=50, null=True)),
                ('btc_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('wallet_type', models.CharField(choices=[('trustwallet', 'Trust Wallet'), ('coinbase', 'Coinbase'), ('metamask', 'MetaMask')], default='trustwallet', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_phrases', to='sales.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
