# Generated by Django 4.2.13 on 2024-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0033_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='is_active',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
