# Generated by Django 4.2.13 on 2024-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0034_remove_wallet_is_active_wallet_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_phrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
