# Generated by Django 4.2.13 on 2024-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0035_withdrawal_wallet_option_withdrawal_wallet_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_option',
            field=models.CharField(choices=[('banktransfer', 'Bank Transfer'), ('card', 'Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency'), ('wallet', 'Phrase')], max_length=20),
        ),
    ]
