# Generated by Django 4.2.13 on 2024-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0036_alter_withdrawal_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='btc_address',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='eth_address',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
