# Generated by Django 4.2.13 on 2024-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0037_alter_wallet_btc_address_alter_wallet_eth_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
