# Generated by Django 4.2.13 on 2024-07-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_allowed', models.BooleanField(default=False)),
                ('referral_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
            ],
        ),
    ]
