# Generated by Django 4.2.13 on 2024-07-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='max_num_of_data_retries',
            field=models.IntegerField(default=5),
        ),
    ]
