# Generated by Django 4.2.13 on 2024-07-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0002_websitesettings_max_num_of_data_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
