# Generated by Django 4.2.13 on 2024-07-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0003_websitesettings_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
