# Generated by Django 4.2.13 on 2024-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0004_websitesettings_support_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='investment_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
