# Generated by Django 4.2.13 on 2024-07-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0005_websitesettings_investment_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='investment_withdrawal_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
