# Generated by Django 5.1 on 2024-08-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0006_websitesettings_investment_withdrawal_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='maintenance_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
