# Generated by Django 5.1 on 2024-08-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0007_websitesettings_maintenance_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='merchant_referral_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='merchant_referral_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
