# Generated by Django 5.1 on 2024-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0008_websitesettings_merchant_referral_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='referral_withdrawal_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
