# Generated by Django 5.1 on 2024-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0009_websitesettings_referral_withdrawal_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='referral_withdrawal_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
