# Generated by Django 4.2.13 on 2024-09-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0011_investmentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='deposit_address',
            field=models.CharField(blank=True, default='0x4e5acf9684652BEa56F2f01b7101a225Ee33d23f', max_length=50, null=True),
        ),
    ]
