# Generated by Django 4.2.13 on 2024-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0012_websitesettings_deposit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsetting',
            name='withdrawal_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
